Almost FIFO
scalable-arch/100kSV pull request #15
Opened 2023-09-28 16:15 UTC by junseung2

Almost FIFO 추가하였습니다.

2023-10-06 04:30 UTC, dale40 requested changes

2023-10-06 04:30 UTC, dale40 commented on FIFO/ALMOST_FIFO/almost_FIFO.sv
> +        almost_full                 = (counter_n >= ALMOST_FULL_LEVEL);
almost_empy가 아니고 almost_empty_n으로 assign하고 F/F으로 한번 채주세요
almost_full 도 마찬가지.

2024-07-26 04:28 UTC, dale40 commented
@junseung2 이거 업데이트 해줘.

2024-07-29 08:03 UTC, junseung2 commented
업데이트 완료했습니다.

2024-11-01 05:09 UTC, closed without merging